# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import market_pb2 as market__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketplaceControllerStub(object):
    """Centralized Controller
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/marketplace.MarketplaceController/Heartbeat',
                request_serializer=market__pb2.Ping.SerializeToString,
                response_deserializer=market__pb2.Pong.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/marketplace.MarketplaceController/CreateItem',
                request_serializer=market__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.MarketplaceController/GetItem',
                request_serializer=market__pb2.GetItemRequest.SerializeToString,
                response_deserializer=market__pb2.MarketplaceItem.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/marketplace.MarketplaceController/SearchItems',
                request_serializer=market__pb2.SearchRequest.SerializeToString,
                response_deserializer=market__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/marketplace.MarketplaceController/UpdateItem',
                request_serializer=market__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/marketplace.MarketplaceController/PlaceBid',
                request_serializer=market__pb2.BidRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.unary_stream(
                '/marketplace.MarketplaceController/JoinAuction',
                request_serializer=market__pb2.AuctionRequest.SerializeToString,
                response_deserializer=market__pb2.AuctionEvent.FromString,
                _registered_method=True)
        self.GetPrimaryStorage = channel.unary_unary(
                '/marketplace.MarketplaceController/GetPrimaryStorage',
                request_serializer=market__pb2.GetPrimaryStorageRequest.SerializeToString,
                response_deserializer=market__pb2.GetPrimaryStorageResponse.FromString,
                _registered_method=True)


class MarketplaceControllerServicer(object):
    """Centralized Controller
    """

    def Heartbeat(self, request, context):
        """Health check endpoint for monitoring service node health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Add a new item listing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Retrieve current state of a specific item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Search items by keyword, category, or filter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Update item metadata (description, quantity, status)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Submit a bid on an auction-enabled item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request, context):
        """Persistent Auction Participation
        Join an auction and receive a stream of updates whenever the state changes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrimaryStorage(self, request, context):
        """getting the primary storage node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketplaceControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=market__pb2.Ping.FromString,
                    response_serializer=market__pb2.Pong.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=market__pb2.CreateItemRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=market__pb2.GetItemRequest.FromString,
                    response_serializer=market__pb2.MarketplaceItem.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=market__pb2.SearchRequest.FromString,
                    response_serializer=market__pb2.SearchResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=market__pb2.UpdateItemRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=market__pb2.BidRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=market__pb2.AuctionRequest.FromString,
                    response_serializer=market__pb2.AuctionEvent.SerializeToString,
            ),
            'GetPrimaryStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimaryStorage,
                    request_deserializer=market__pb2.GetPrimaryStorageRequest.FromString,
                    response_serializer=market__pb2.GetPrimaryStorageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.MarketplaceController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.MarketplaceController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketplaceController(object):
    """Centralized Controller
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceController/Heartbeat',
            market__pb2.Ping.SerializeToString,
            market__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceController/CreateItem',
            market__pb2.CreateItemRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceController/GetItem',
            market__pb2.GetItemRequest.SerializeToString,
            market__pb2.MarketplaceItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceController/SearchItems',
            market__pb2.SearchRequest.SerializeToString,
            market__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceController/UpdateItem',
            market__pb2.UpdateItemRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceController/PlaceBid',
            market__pb2.BidRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketplace.MarketplaceController/JoinAuction',
            market__pb2.AuctionRequest.SerializeToString,
            market__pb2.AuctionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrimaryStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceController/GetPrimaryStorage',
            market__pb2.GetPrimaryStorageRequest.SerializeToString,
            market__pb2.GetPrimaryStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MarketplaceServiceStub(object):
    """Service Layer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/marketplace.MarketplaceService/CreateItem',
                request_serializer=market__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.MarketplaceService/GetItem',
                request_serializer=market__pb2.GetItemRequest.SerializeToString,
                response_deserializer=market__pb2.MarketplaceItem.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/marketplace.MarketplaceService/SearchItems',
                request_serializer=market__pb2.SearchRequest.SerializeToString,
                response_deserializer=market__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/marketplace.MarketplaceService/UpdateItem',
                request_serializer=market__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/marketplace.MarketplaceService/PlaceBid',
                request_serializer=market__pb2.BidRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.unary_stream(
                '/marketplace.MarketplaceService/JoinAuction',
                request_serializer=market__pb2.AuctionRequest.SerializeToString,
                response_deserializer=market__pb2.AuctionEvent.FromString,
                _registered_method=True)


class MarketplaceServiceServicer(object):
    """Service Layer
    """

    def CreateItem(self, request, context):
        """Add a new item listing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Retrieve current state of a specific item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Search items by keyword, category, or filter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Update item metadata (description, quantity, status)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Submit a bid on an auction-enabled item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request, context):
        """Persistent Auction Participation
        Join an auction and receive a stream of updates whenever the state changes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketplaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=market__pb2.CreateItemRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=market__pb2.GetItemRequest.FromString,
                    response_serializer=market__pb2.MarketplaceItem.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=market__pb2.SearchRequest.FromString,
                    response_serializer=market__pb2.SearchResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=market__pb2.UpdateItemRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=market__pb2.BidRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=market__pb2.AuctionRequest.FromString,
                    response_serializer=market__pb2.AuctionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.MarketplaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.MarketplaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketplaceService(object):
    """Service Layer
    """

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceService/CreateItem',
            market__pb2.CreateItemRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceService/GetItem',
            market__pb2.GetItemRequest.SerializeToString,
            market__pb2.MarketplaceItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceService/SearchItems',
            market__pb2.SearchRequest.SerializeToString,
            market__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceService/UpdateItem',
            market__pb2.UpdateItemRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceService/PlaceBid',
            market__pb2.BidRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketplace.MarketplaceService/JoinAuction',
            market__pb2.AuctionRequest.SerializeToString,
            market__pb2.AuctionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MarketplaceStorageStub(object):
    """Storage Layer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplicateState = channel.unary_stream(
                '/marketplace.MarketplaceStorage/ReplicateState',
                request_serializer=market__pb2.ReplicationRequest.SerializeToString,
                response_deserializer=market__pb2.MarketplaceItem.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/marketplace.MarketplaceStorage/CreateItem',
                request_serializer=market__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.MarketplaceStorage/GetItem',
                request_serializer=market__pb2.GetItemRequest.SerializeToString,
                response_deserializer=market__pb2.MarketplaceItem.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/marketplace.MarketplaceStorage/DeleteItem',
                request_serializer=market__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/marketplace.MarketplaceStorage/SearchItems',
                request_serializer=market__pb2.SearchRequest.SerializeToString,
                response_deserializer=market__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/marketplace.MarketplaceStorage/UpdateItem',
                request_serializer=market__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/marketplace.MarketplaceStorage/PlaceBid',
                request_serializer=market__pb2.BidRequest.SerializeToString,
                response_deserializer=market__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.unary_stream(
                '/marketplace.MarketplaceStorage/JoinAuction',
                request_serializer=market__pb2.AuctionRequest.SerializeToString,
                response_deserializer=market__pb2.AuctionEvent.FromString,
                _registered_method=True)


class MarketplaceStorageServicer(object):
    """Storage Layer
    """

    def ReplicateState(self, request, context):
        """Replication endpoint for synchronizing replicas with primary storage state changes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Add a new item listing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Retrieve current state of a specific item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Delete an item listing (used for rollback during replication failure)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Search items by keyword, category, or filter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Update item metadata (description, quantity, status)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Submit a bid on an auction-enabled item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request, context):
        """Persistent Auction Participation
        Join an auction and receive a stream of updates whenever the state changes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketplaceStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplicateState': grpc.unary_stream_rpc_method_handler(
                    servicer.ReplicateState,
                    request_deserializer=market__pb2.ReplicationRequest.FromString,
                    response_serializer=market__pb2.MarketplaceItem.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=market__pb2.CreateItemRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=market__pb2.GetItemRequest.FromString,
                    response_serializer=market__pb2.MarketplaceItem.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=market__pb2.DeleteItemRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=market__pb2.SearchRequest.FromString,
                    response_serializer=market__pb2.SearchResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=market__pb2.UpdateItemRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=market__pb2.BidRequest.FromString,
                    response_serializer=market__pb2.ActionResponse.SerializeToString,
            ),
            'JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=market__pb2.AuctionRequest.FromString,
                    response_serializer=market__pb2.AuctionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.MarketplaceStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.MarketplaceStorage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketplaceStorage(object):
    """Storage Layer
    """

    @staticmethod
    def ReplicateState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketplace.MarketplaceStorage/ReplicateState',
            market__pb2.ReplicationRequest.SerializeToString,
            market__pb2.MarketplaceItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceStorage/CreateItem',
            market__pb2.CreateItemRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceStorage/GetItem',
            market__pb2.GetItemRequest.SerializeToString,
            market__pb2.MarketplaceItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceStorage/DeleteItem',
            market__pb2.DeleteItemRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceStorage/SearchItems',
            market__pb2.SearchRequest.SerializeToString,
            market__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceStorage/UpdateItem',
            market__pb2.UpdateItemRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.MarketplaceStorage/PlaceBid',
            market__pb2.BidRequest.SerializeToString,
            market__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketplace.MarketplaceStorage/JoinAuction',
            market__pb2.AuctionRequest.SerializeToString,
            market__pb2.AuctionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
